package com.ty.school.dao;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityTransaction;
import javax.persistence.Persistence;

import com.ty.school.dto.Student;
import com.ty.school.dto.User;

public class UserDao {
	User saveUser(User user) {
		User u1=new User();
		//u1.setId(1);->AutoGenerated
		u1.setEmail("dixithsn123@gmail.com");
		u1.setGender("M");
		u1.setPassword("DixITh@SN");
		u1.setPhone(9877635321l);
		User u2=new User();
		//u2.setId(2);
		u2.setEmail("vikash123@gmail.com");
		u2.setGender("M");
		u2.setPassword("viKAsh@123");
		u2.setPhone(9877224321l);
		User u3=new User();
		//u3.setId(3);
		u3.setEmail("vishal123@gmail.com");
		u3.setGender("M");
		u3.setPassword("VISHal@123");
		u3.setPhone(9877635211l);
		
		User u4=new User();
		//u4.setId(4);->AutoGenerated
		u4.setEmail("vinod123@gmail.com");
		u4.setGender("M");
		u4.setPassword("vINOD@123");
		u4.setPhone(9333635321l);
		EntityManagerFactory emf=Persistence.createEntityManagerFactory("vikas");
		System.out.println(emf);
		EntityManager em=emf.createEntityManager();
		EntityTransaction et=em.getTransaction();
		et.begin();
		em.persist(u1);
		em.persist(u2);
		em.persist(u3);
		em.persist(u4);
		et.commit();

		return user;
		
	}
		User findUserById(int id) {
			EntityManagerFactory emf=Persistence.createEntityManagerFactory("vikas");
			EntityManager em=emf.createEntityManager();
			User u=em.find(User.class,5);
			if(u!=null) {
			System.out.println(u.getId());
			System.out.println(u.getEmail());
			System.out.println(u.getPassword());
			System.out.println(u.getPhone());
			System.out.println(u.getGender());
			}
			else
				System.out.println("Id does not exist");
			return null;
	}
		boolean deleteUser(int id) {
			EntityManagerFactory emf=Persistence.createEntityManagerFactory("vikas");
			//System.out.println(emf);
			EntityManager em=emf.createEntityManager();
			EntityTransaction et=em.getTransaction();
			User u=em.find(User.class,4);
			if(u!=null) {
				et.begin();
				em.remove(u);
				et.commit();
				System.out.println("User Deleted");
			}
			else {
				System.out.println("Id does not exist");
			}
			return false;
			
		}
		User updateUser(User user) {
			User u=new User();
			u.setEmail("shivam123@gmail.com");
			u.setGender("M");
			u.setPassword("shivam@123");
			u.setPhone(9977633331l);
			EntityManagerFactory emf=Persistence.createEntityManagerFactory("vikas");
			//System.out.println(emf);
			EntityManager em=emf.createEntityManager();
			EntityTransaction et=em.getTransaction();
			et.begin();
			em.merge(u);
			et.commit();
			
			return user;
			
		}

}
